### ISSUE TITLE
Bad Gateway When Trying to Download Dataset

### ISSUE THREAD

**Issue by ghost** [msukmanowsky/pyconca-2016-spark-tutorial#2]
There is currently a 502 Bad Gateway here https://figshare.com/articles/Wikipedia_Clickstream/1305770. Is there an alternate link for the dataset?

**Comment by msukmanowsky** [comment]
Hmm it's still working for me. Could you try again @weirwolf?

**Comment by ghost** [comment]
In a rush to travel to the event from out of town. Great presentation.
